### ISSUE TITLE
Spring context is not loading when Loki server is not accessible

### ISSUE THREAD

**Issue by andrey-nakin** [loki4j/loki-logback-appender#133]
If my Loki server in unavailable (for any reason), the Spring Boot application does not start due to the following error:

```
Caused by: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in com.github.loki4j.client.pipeline.DefaultPipeline@4d55f6d8 - Error while sending Batch #6f89cb4afb3d (8 291 bytes) to Loki (http://my.loki.server.net/loki/api/v1/push) java.net.ConnectException
at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:169)
...
```

Can it be more tolerate to the network errors that can be temporary?

**Comment by nehaev** [comment]
Hi @andrey-nakin, thanks for reporting!

Could you please provide the full stack trace for this IllegalStateException? Most likely it's caused by the real configuration issue.

The ERROR log line doesn't relate to IllegalStateException as it's just a log line. Log4j doesn't throw any exceptions in case sending failed, only writes an error to log. You can check the corresponding code here: https://github.com/loki4j/loki-logback-appender/blob/main/loki-client/src/main/java/com/github/loki4j/client/pipeline/DefaultPipeline.java#L269
