### ISSUE TITLE
multi-tenant loki requires X-Scope-OrgID http header during call to Loki API

### ISSUE THREAD

**Issue by ramazanyich** [loki4j/loki-logback-appender#64]
as described in https://grafana.com/docs/loki/latest/operations/multi-tenancy/  in multitenant Loki setup requests to the Loki API should include an HTTP header (X-Scope-OrgID) that identifies the tenant for the request.

Please add possibility to add the http header during pushing the message using loki4j appender.

We have a multitenant service which send log messages to the multitenant loki server. 
currently JavaHttpAdapter can send only message itself as a body using sendAsync call. 
Maybe  some MDC context key/value can be used to set the header during logging of the message ?
Something like that can be used during logging of message:
```
MDC.put("LOKI.TENANT",tenantname)
try{
log.info("test")
}finally{
MDC.clear()
}
```
and during send logappender implementation can read that MDC key and set it as X-Scope-OrgID http header.. 
Or any other way ?

**Comment by nehaev** [comment]
Thanks for reporting, @ramazanyich!

I've summed up what needs to be done for a multi-tenancy support in #65. Please drop a comment there if you'd like to prepare a PR for this.

`tenantId` will be statically configured for the appender. However, if you need multiple tenants inside one project, you can have multiple appenders (with different `tenantId` configured) and route log messages between them using [filters](http://logback.qos.ch/manual/filters.html).

If what you need is just to be able to filter log messages based on MDC, there is another alternative that is already supported by Loki4j: label patterns. You can use them like this:

```xml
    <appender name="LOKI" class="com.github.loki4j.logback.Loki4jAppender">
        ...
        <format>
            <label>
                <pattern>level=%level,host=${HOSTNAME},service=%X{SERVICE.NAME:-unknown}</pattern>
            </label>
        </format>
    </appender>
```

Then you can query logs based on label: `{service="my-service"}`.

**Comment by nehaev** [comment]
> Thanks for fast response!
Have one concern with solution:
It looks good for small amount of tenants which are static.
In our case we can have many tenants (currently about 50, but we will have more of them...) and they are dynamic (can be added/removed).
So I see two issues:
first - static config, but that one we can manage as we construct our loki4j appender using our internal code (not xml config).
second - is the resources usage. Per http sender there is a http thread pool currently in Loki4j. So if there are 100 tenants then it is already at least 100 threads... and that number is growing with number of tenants.. We use just one Loki server which will be configured for multi-tenancy, so one thread pool with some decent amount of threads should be enough. Just header should be changing during log record sending.
that second concern is kind of hitting..


Ok, so if I got this right:

1. You can not use static tenant config because in your case tenants are dynamic
2. You can not use dynamic labels because you need a strict isolation between these groups of messages

Well, I guess this case goes beyond a typical usage of logging appender. Introducing dynamic tenants to Loki4j will add one more level of complexity along with sorting by time and grouping by lables. And that is something I would like to avoid by now. Probably the best option would be just to write your own client for Loki API. It could be simple enough as it doesn't seem to need most of the Loki4j's features.
